### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [sanex3339/webpack-js-obfuscator#1]
Hello,

I tried to use your plugin while using https://github.com/AngularClass/angular2-webpack-starter
When I do a npm run build:prod , there is no /dist folder created, however build fails silently.
Any ideas what I did wrong?

Thanks for the plugin!
Kind regards,

Lander

I've added it like follows in the webpack.prod.js config file:

      /**
       * Plugin LoaderOptionsPlugin (experimental)
       *
       * See: https://gist.github.com/sokra/27b24881210b56bbaff7
       */
      new LoaderOptionsPlugin({
        debug: false,
        options: {

          /**
           * Static analysis linter for TypeScript advanced options configuration
           * Description: An extensible linter for the TypeScript language.
           *
           * See: https://github.com/wbuchwalter/tslint-loader
           */
          tslint: {
            emitErrors: true,
            failOnHint: true,
            resourcePath: 'src'
          },

          /**
           * Html loader advanced options
           *
           * See: https://github.com/webpack/html-loader#advanced-options
           */
          // TODO: Need to workaround Angular 2's html syntax => #id [bind] (event) *ngFor
          htmlLoader: {
            minimize: true,
            removeAttributeQuotes: false,
            caseSensitive: true,
            customAttrSurround: [
              [/#/, /(?:)/],
              [/\*/, /(?:)/],
              [/\[?\(?/, /(?:)/]
            ],
            customAttrAssign: [/\)?\]?=/]
          },

        }
      }),

      new WebpackJsObfuscator({}, []),

    ],

    /*
     * Include polyfills or mocks for various node stuff
     * Description: Node configuration
     *
     * See: https://webpack.github.io/docs/configuration.html#node
     */
    node: {
      global: true,
      crypto: 'empty',
      process: false,
      module: false,
      clearImmediate: false,
      setImmediate: false
    }

  });
}

**Comment by sanex3339** [comment]
Hi, better use this plugin:
https://github.com/javascript-obfuscator/webpack-obfuscator

I will not support `webpack-js-obfuscator`

**Comment by LanderBeeuwsaert** [comment]
Cool, thanks, I'll try.
